spring:
  application:
    name: tusa
  datasource:
    # connect database
    url: jdbc:postgresql://localhost:5432/tusa_db
    username: postgres
    password: adminadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
